### ISSUE TITLE
pamin not installed

### ISSUE THREAD

**Issue by thisnugroho** [navotera/BashServerSetup#3]
Pamin tidak terinstall, hanya file `pamin.service` saja yang di copy ke `/etc/systemd/system/`

tapi tidak ada folder `/pamin` didalam `/etc`

**Comment by thisnugroho** [comment]
Solution:
1. Download latest pamin
2. Extract
3. Rename folder name to pamin
4. move to `/etc`
5. restart service `service pamin restart`

**Comment by navotera** [comment]
fixed
